import { spawn } from "node:child_process";
import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import electron from "electron";
const packaged = process.argv[2];
const mode = process.argv[3] || "overlay";
if (!["overlay", "pet"].includes(mode)) throw Error("Expected overlay or pet");
const dir = path.resolve("test-results", `${mode}-${Date.now()}`);
await mkdir(dir, { recursive: true });
const env = { ...process.env, ONGI_DATA_DIR: dir };
delete env.ELECTRON_RUN_AS_NODE;
const child = spawn(packaged || electron, [...(packaged ? [] : ["."]), `--${mode}-smoke`], {env, stdio:"inherit"});
const timer = setTimeout(() => { child.kill(); }, 60000);
const code = await new Promise((resolve, reject) => { child.once("error", reject); child.once("exit", resolve); });
clearTimeout(timer);
if (code !== 0) throw Error(`Desktop smoke exited ${code}`);
const result = JSON.parse(await readFile(path.join(dir, `${mode}-smoke.json`), "utf8"));
if (!(result.passed || result.ready)) throw Error("Missing successful smoke result");
console.log(`Verified ${packaged || "development app"}: ${dir}`);
